{% set name = "pytest-regressions" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e3dce521fac11199a2a91a1b8837974d708c7e8665b8c9668b3a721b556c8183

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm

  run:
    - pytest >=6.2.0
    - pytest-datadir >=1.2.0
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pandas
    - pillow
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - pytest_regressions
  commands:
    - pytest tests

about:
  home: https://github.com/ESSS/pytest-regressions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use fixtures to write regression tests.
  description: Easy to use fixtures to write regression tests.

extra:
  recipe-maintainers:
    - alexandrebbruno
    - igortg
    - nicoddemus
    - tadeu
